/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lcmt_discrete_particle_u implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public double force;
 
    public lcmt_discrete_particle_u()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x813195c6521f32b8L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.lcmt_discrete_particle_u.class))
            return 0L;
 
        classes.add(lcmtypes.lcmt_discrete_particle_u.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeDouble(this.force); 
 
    }
 
    public lcmt_discrete_particle_u(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lcmt_discrete_particle_u(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.lcmt_discrete_particle_u _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.lcmt_discrete_particle_u o = new lcmtypes.lcmt_discrete_particle_u();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.force = ins.readDouble();
 
    }
 
    public lcmtypes.lcmt_discrete_particle_u copy()
    {
        lcmtypes.lcmt_discrete_particle_u outobj = new lcmtypes.lcmt_discrete_particle_u();
        outobj.timestamp = this.timestamp;
 
        outobj.force = this.force;
 
        return outobj;
    }
 
}

