/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lcmt_discrete_particle_x implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public double q;
    public double v;
 
    public lcmt_discrete_particle_x()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x79fbd7214e23a31aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.lcmt_discrete_particle_x.class))
            return 0L;
 
        classes.add(lcmtypes.lcmt_discrete_particle_x.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeDouble(this.q); 
 
        outs.writeDouble(this.v); 
 
    }
 
    public lcmt_discrete_particle_x(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lcmt_discrete_particle_x(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.lcmt_discrete_particle_x _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.lcmt_discrete_particle_x o = new lcmtypes.lcmt_discrete_particle_x();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.q = ins.readDouble();
 
        this.v = ins.readDouble();
 
    }
 
    public lcmtypes.lcmt_discrete_particle_x copy()
    {
        lcmtypes.lcmt_discrete_particle_x outobj = new lcmtypes.lcmt_discrete_particle_x();
        outobj.timestamp = this.timestamp;
 
        outobj.q = this.q;
 
        outobj.v = this.v;
 
        return outobj;
    }
 
}

