"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_discrete_particle_x(object):
    __slots__ = ["timestamp", "q", "v"]

    __typenames__ = ["int64_t", "double", "double"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.q = 0.0
        self.v = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_discrete_particle_x._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdd", self.timestamp, self.q, self.v))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_discrete_particle_x._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_discrete_particle_x._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_discrete_particle_x()
        self.timestamp, self.q, self.v = struct.unpack(">qdd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lcmt_discrete_particle_x in parents: return 0
        tmphash = (0x79fbd7214e23a31a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_discrete_particle_x._packed_fingerprint is None:
            lcmt_discrete_particle_x._packed_fingerprint = struct.pack(">Q", lcmt_discrete_particle_x._get_hash_recursive([]))
        return lcmt_discrete_particle_x._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_discrete_particle_x._get_packed_fingerprint())[0]

